api/urls.py
from django.urls import path
from .views import UserProfileList
from . import views

urlpatterns = [
    path('user_profile/', UserProfileList.as_view(), name='user_profile'),

]

authenticate/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from salesdashboard import settings

from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('user/', views.UserList, name='user'),
    path('create_user/',views.Create_User, name='create_user'),
    path('update-user-info/<int:user_id>/', views.update_user_info, name='update_user_info'),
    path('view-user/<int:user_id>', views.view_user, name='view_user'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="authenticate/reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="authenticate/reset_password_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="authenticate/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="authenticate/password_reset_complete.html"),
         name="password_reset_complete"),

]

salesdashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from salesdashboard import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/', include('authenticate.urls')),
    path('', include('homedash.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticate/models.py
from django.db import models
from django.contrib.auth.models import User


class SalesCategory(models.Model):
    type = models.CharField(max_length=50)
    def __str__(self):
        return self.type

    def delete(self, *args, **kwargs):
        print(f"Deleting SalesCategory: {self.id}")
        super().delete(*args, **kwargs)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    full_name = models.CharField(max_length=264, blank=True)
    job_title = models.CharField(max_length=264, blank=True)
    head_of_sales = models.ForeignKey(User, on_delete=models.CASCADE, related_name="head_of_sales", blank=True, null=True)
    pin = models.IntegerField(null=False, blank=False)
    role_choices = (
            ("CEO", "Management"),
            ("HOS", "Sales Manager"),
            ("Salesperson", "Salesperson"),

    )

    role_type = models.CharField(max_length=265, choices=role_choices, blank=True)
    profile_picture = models.ImageField(upload_to='profile_picture/', blank=True, null=True)
    def __str__(self):
         return self.user.username

authenticate/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from authenticate.models import *

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(
        required=True, label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        required=True, label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password Confirm'})
    )

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')



class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('full_name', 'job_title', 'head_of_sales', 'role_type')

class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture']

authenticate/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.files.storage import default_storage
from django.urls import reverse, reverse_lazy
import os
import logging
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from authenticate.models import UserProfile
from authenticate.forms import CreateNewUser, ProfilePictureForm


# Create your views here.

def loginPage(request):
    if request.user.is_superuser:
        messages.error(request, 'You are a superuser')
        return HttpResponseRedirect('login')
    else:
        if request.user.is_authenticated:
            return redirect('/')

        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is None:
                messages.info(request, 'Username or password wrong')
                return redirect('login')
            else:
                login(request, user)
                return redirect('/')

    return render(request, 'authenticate/login.html')


@login_required(login_url='/authenticate/login/')
def Create_User(request):
    form = CreateNewUser()
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            email = request.POST['email']
            username = request.POST['username']
            password = request.POST['password1']

            pin = request.POST['pin']
            if UserProfile.objects.filter(pin=pin).exists():
                messages.info(request, 'PIN already exists')
                return redirect('create_user')

            user = User.objects.create_user(username=username, password=password, email=email)
            user.save()
            data_dict = {
                'user_id': user.id,
                'full_name': request.POST['full_name'],
                'job_title': request.POST['job_title'],
                'pin': pin,
                'role_type': request.POST['role_type'],
            }
            UserProfile.objects.create(**data_dict, head_of_sales_id=request.user.id)
            return redirect('user')

    return render(request, "authenticate/create_user.html", {'form': form})


@login_required(login_url='/authenticate/login/')
def UserList(request):
    if request.user.user_profile.role_type == 'HOS':
        hos_user = request.user
        users = UserProfile.objects.filter(role_type='Salesperson', head_of_sales=hos_user)

    elif request.user.user_profile.role_type == 'CEO':
        users = UserProfile.objects.exclude(role_type='CEO')

    else:
        raise Http404('Access Denied')

    if request.method == 'GET':
        username = request.GET.get('username', '')
        query = Q()
        # Filter based on the 'user' field in UserProfile
        query &= Q(user__username=username)
        results = UserProfile.objects.filter(query)

    diction = {
        'title': 'User List',
        'users': users,
        'results': results
    }

    return render(request, "authenticate/user.html", context=diction)

@login_required(login_url='/authenticate/login/')
def update_user_info(request, user_id):
    user_profile = UserProfile.objects.get(pk=user_id)


    if request.method == 'POST':

        user_profile.full_name = request.POST.get('full_name')
        user_profile.job_title = request.POST.get('job_title')
        user_profile.role_type = request.POST.get('role_type')


        user_profile.save()
        user_email = user_profile.user.email

        return redirect('user')

    return render(request, "authenticate/update_user_info.html",{'user_profile': user_profile})

@login_required(login_url='/authenticate/login/')
def view_user(request, user_id):
    user_profile = UserProfile.objects.get(pk=user_id)
    return render(request, "authenticate/view_user.html", {'user_profile': user_profile})


@login_required(login_url='/authenticate/login/')
def profile(request):
    user = request.user
    user_profile = UserProfile.objects.get(user=user)

    if request.method == 'POST':
        form = ProfilePictureForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            # Check if there's an existing profile picture to remove
            if user_profile.profile_picture:
                # Remove the existing profile picture file
                default_storage.delete(user_profile.profile_picture.name)

            # Save the new profile picture
            profile_picture = form.cleaned_data.get('profile_picture')
            if profile_picture:
                user_profile.profile_picture = profile_picture
            else:
                user_profile.profile_picture = None

            user_profile.save()
            return redirect('profile')
    else:
        form = ProfilePictureForm(instance=user_profile)

    return render(request, "authenticate/profile.html", {'user': user, 'user_profile': user_profile, 'form': form})


@login_required(login_url='/authenticate/login/')
def edit_profile(request):
    user_profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        user_profile.full_name = request.POST.get('full_name')
        user_profile.job_title = request.POST.get('job_title')
        user_profile.role_type = request.POST.get('role_type')

        user_profile.save()

        return redirect('profile')

    return render(request, "authenticate/edit_profile.html", {'user_profile': user_profile})


@login_required(login_url='/authenticate/login/')
def logoutUser(request):
    logout(request)
    return redirect('login')

templates/authenticate/create_user.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}

<!-- Specific CSS goes HERE -->

{% block content %}
    <center xmlns="http://www.w3.org/1999/html">
        <div class="col-xl-8">
            <div class="create_up">
                <h3>Create User </h3>
                <hr>
                <form method="post" >
                {{ form|crispy }}
                {% csrf_token %}
                <div id="div_id_pin" class="form-group">
                    <div class="">
                        <input type="number" placeholder="PIN" id="pin" class="textinput textInput select form-control" name="pin" required>
                    </div>
                </div>
                <div id="div_id_full-name" class="form-group">
                    <div class="">
                        <input type="text" placeholder="Full Name" id="full_name" class="textinput textInput select form-control" name="full_name" required>
                    </div>
                </div>
                <div id="div_id_job-title" class="form-group">
                    <div class="">
                        <input type="text" placeholder="Job Title" id="job_title" class="textinput textInput select form-control" name="job_title" required>
                    </div>
                </div>
                <div id="div_id_hos" class="form-group">
                    <div class="">
                        <input type="text" placeholder="Head of Sales" value="{{ request.user }}" id="head_of_sales" class="textinput textInput select form-control" name="head_of_sales" required>
                    </div>
                </div>
                <div id="div_id_type" class="form-group">
                    <div class="">
                        <select name="role_type" class="textinput textInput select form-control" required id="id_type">
                            <option value="">-----Select User Role----</option>
                            <option value="CEO">Management</option>
                            <option value="HOS">Sales Manager</option>
                            <option value="Salesperson">Salesperson</option>
                        </select>
                    </div>
                </div>
                <button type="submit" style="width: 100%" class="btn btn-primary">Create</button>
                {% for message in messages %}
                    <p id="messages" style="color:white">{{message}}</p>
                {% endfor %}
                </form>
            </div>
        </div>
    </center>
{% endblock %}

templates/authenticate/edit_profile.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
<div class="row gutters">
<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
<div class="card h-100">
	<div class="card-body">
		<div class="account-settings text-center">
			<div class="user-profile">
				<div class="user-avatar">
					<img src="{{ user_profile.profile_picture.url }}" alt="Maxwell Admin" class="rounded-circle img-thumbnail" style="max-width: 190px;">
				</div>
			</div>
			<div class="user-information-2 p-4" style="margin-top: 50px; padding-top: 20px">
				<h3 class="user-name" style="font-size: 24px;">{{ user_profile.user.username }}</h3>
				<h4 class="user-fullname" style="font-size: 24; color: grey;">{{ user_profile.full_name }}</h4>
				<h5 class="user-email" style="font-size: 14px; color: grey;">Email: {{ user_profile.user.email }}</h5>
			</div>
		</div>
	</div>
</div>
</div>
<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
<div class="card h-100">
	<div class="card-body">
		<div class="row gutters">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
				<h6 class="mb-2 text-primary">Personal Details</h6>
			</div>
			<form method="post" class="form">
				{% csrf_token %}
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<div class="form-group">
						<label for="full_name">Full Name:</label>
    					<input type="text" id="full_name" name="full_name" value="{{ user_profile.full_name }}"><br>
					</div>
					<div class="form-group">
						<label for="job_title">Job Title:</label>
    					<input type="text" id="job_title" name="job_title" value="{{ user_profile.job_title }}"><br>
					</div>
				</div>
				<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
					<div class="form-group">
						<label for="role_type">Role Type:</label>
						<select id="role_type" name="role_type">
							{% for choice in user_profile.role_choices %}
								<option value="{{ choice.0 }}" {% if choice.0 == user_profile.role_type %}selected{% endif %}>
									{{ choice.1 }}
								</option>
							{% endfor %}
						</select><br>
					</div>
				</div>
				<div class="row gutters">
					<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
						<div class="text-right">
							<button type="submit" class="btn btn-primary">Update</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
</div>
</div>
</div>
{% endblock %}

templates/authenticate/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>
   <div class="login-box">
    <h2>Login</h2>
    <form method="POST" id="loginForm" action="">
        {% csrf_token %}
        <div class="user-box">
            <input type="text" name="username" id="username" required="" >
            <label>Username</label>
        </div>
        <div class="user-box">
            <input type="password" name="password" id="password" required="" >
            <label>Password</label>
        </div>
        <div class="container">
                <button class="btn btn-login" name="login" type="submit" value="Login">Login</button>
        </div>

        {% for message in messages %}
            <p id="messages" style="color:white">{{message}}</p>
        {% endfor %}
    </form>
        <div class="row mt-3">
            <div class="col-6">
              <small> </small>
            </div>
            <div class="col-6 text-right">
              <a href="{% url 'reset_password' %}" class="text-light"><small>Reset Password</small></a>
            </div>
          </div>
   </div>
</body>
</html>

templates/authenticate/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <style>
        html {
            height: 100%;
        }
        body {
            margin:0;
            padding:0;
            font-family: sans-serif;
            background: linear-gradient(#141e30, #243b55);
        }

        h3{
            color: #fff;
            padding: 50px;
        }

        h5{
            color: #fff;
            padding: 50px;
        }

        a.login-link {
            display: inline-block;
            padding: 10px 20px;
            background-color: orange;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

        a.login-link:hover {
            background-color: darkorange;
        }
</style>
</head>
<body>
    <h3>
        Password Complete
    </h3>
    <h5>
        Your password has been set. You may go ahead and log in now.
    </h5>
    <h5>
        <a class="login-link" href="{% url 'login' %}">Log In</a>
    </h5>
</body>
</html>

templates/authenticate/profile.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container" xmlns="http://www.w3.org/1999/html">
<div class="row gutters">
<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
	<div class="card h-100">
	<div class="card-body">
		<div class="account-settings text-center">
			<div class="user-profile">
				<label for="profile_picture">
					<div class="profile-picture-container">
						{% if not user_profile.profile_picture %}
							<img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="{{ user_profile.user.username }}" class="rounded-circle img-thumbnail" style="max-width: 190px;">
						{% else %}
							<img src="{{ user_profile.profile_picture.url }}" alt="{{ user_profile.user.username }}" class="rounded-circle img-thumbnail">
						{% endif %}
						<div class="overlay">
							<i class="fas fa-camera camera-icon" style="border: 2px solid #fff; border-radius: 50%; padding: 5px;"></i>
						</div>
					</div>
				</label>
				<input type="text" id="profile_picture" name="profile_picture" style="display: none;" accept="image/*" data-toggle="modal" data-target="#addCategoryModal">
			</div>
			<div class="user-information-2 p-4" style="margin-top: 50px; padding-top: 20px">
				<h3 class="user-name" style="font-size: 24px;">{{ user_profile.user.username }}</h3>
				<h4 class="user-fullname" style="font-size: 24; color: grey;">{{ user_profile.full_name }}</h4>
				<h5 class="user-email" style="font-size: 14px; color: grey;">Email: {{ user_profile.user.email }}</h5>
			</div>
		</div>
	</div>
</div>
</div>
<div class="modal fade" id="addCategoryModal" tabindex="-1" role="dialog" aria-labelledby="addCategoryModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="addCategoryModalLabel">Add Profile Picture</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <form method="post" class="form" enctype="multipart/form-data">
                        {% csrf_token %}
						{{ form|crispy }}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
<div class="card h-100">
	<div class="card-body">
		<div class="tab-content">
			<div class="row">
				<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
					<h4 class="mb-2 text-primary">Personal Details</h4>
				</div>
				<div class="col-md-4 col-sm-4">
					<h4 class="user-job mb-2"><strong>Job Title:</strong></h4>
				</div>
				<div class="col-md-4 col-sm-4" style="padding-bottom: 20px;">
					<h4 class="user-job1 mb-2">{{ user_profile.job_title }}</h4>
				</div>
			</div>
			<div class="row" style="padding-bottom: 5px;">
				<div class="col-md-4 col-sm-4">
					<h4 class="user-job mb-2" style="padding-bottom: 20px;"><strong>Role:</strong></h4>
				</div>
				<div class="col-md-4 col-sm-4" >
					<h4 class="user-job1 mb-2" style="padding-bottom: 20px;">{{ user_profile.get_role_type_display }}</h4>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-4">
					<h4 class="user-job mb-4" style="padding-bottom: 20px;"><strong>Head of Sales:</strong></h4>
				</div>
				<div class="col-md-4 col-sm-4" >
					<h4 class="user-job1 mb-2" style="padding-bottom: 20px;">{{ user_profile.head_of_sales }}</h4>
				</div>
			</div>
		</div>
        {% if request.user.user_profile.role_type == "HOS" %}
			 <a href="{% url 'edit_profile' %}" class="btn btn-primary btn-bottom-right"style="position: absolute; bottom: 10px; right: 10px; ">Edit</a>
        {% endif %}
	</div>
</div>
</div>
</div>
</div>

{% endblock %}

templates/authenticate/reset_password_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        html {
            height: 100%;
          }
          body {
            margin:0;
            padding:0;
            font-family: sans-serif;
            background: linear-gradient(#141e30, #243b55);
          }
          h3{
             color: #fff;
             padding: 50px;
          }
          h5{
             color: #fff;
             padding: 50px;
          }

    </style>
</head>
<body>
    <h3>
        Password reset sent
    </h3>
    <h5>
        We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
    </h5>
    <h5>
        If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
    </h5>
</body>

</html>

templates/authenticate/user.html
{% extends 'layout/base.html' %}

{% block content %}
    {% if request.user.user_profile.role_type == "HOS" %}
    <div class="container">
        <div class="text-center text-dark">
            <h1>Salesperson List</h1>
        </div>
        <a href="{% url 'create_user' %}" class="btn btn-primary btn-top-right"><i class="fa fa-plus" aria-hidden="true"></i> Add User</a>
    </div>
{% endif %}

<form method="get">
    <div class="input-group md-form form-sm form-1 pl-0">
        <div class="col-md-4">
            <input class="form-control my-2 py-2 mx-2" type="text" id="username" name="username" placeholder="Search by username" aria-label="Search" value="{{ request.GET.username }}">
        </div>
        <div class="input-group-prepend">
            <button class="btn btn-primary my-2 py-2" type="submit">Search</button>
        </div>
    </div>
</form>

{% if results %}
    <h3 class="mt-4">Search Results</h3>
    <table class="table">
        <thead>
            <tr>
                <th>SL.</th>
                <th>Username</th>
                <th>PIN</th>
                <th>Full name</th>
                <th>Role</th>
                <th>Sales Category</th>
                <th>Job Title</th>
                {% if request.user.user_profile.role_type == "HOS" %}
                    <th>Update</th>
                {% endif %}
                <th>View</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in results %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user }}</td>
                    <td>{{ user.pin }}</td>
                    <td>{{ user.full_name }}</td>
                    <td>{{ user.role_type }}</td>
                    <td>{{ user.sales_category }}</td>
                    <td>{{ user.job_title }}</td>
                    {% if request.user.user_profile.role_type == "HOS" %}
                        <td><a href="{% url 'update_user_info' user_id=user.id%}"><i class="fa fa-edit"></i> Update</a></td>
                    {% endif %}
                    <td><a href="{% url 'view_user' user_id=user.id%}"><i class="fa fa-eye" aria-hidden="true"></i> View</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <h3 class="mt-4">All Users</h3>
    <table class="table">
        <!-- Add table header here similar to the search results table -->
        <thead>
            <tr>
                <th>SL.</th>
                <th>Username</th>
                <th>PIN</th>
                <th>Full name</th>
                <th>Role</th>
                <th>Job Title</th>
                {% if request.user.user_profile.role_type == "HOS" %}
                    <th>Update</th>
                {% endif %}
                <th>View</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user }}</td>
                    <td>{{ user.pin }}</td>
                    <td>{{ user.full_name }}</td>
                    <td>{{ user.get_role_type_display }}</td>
                    <td>{{ user.job_title }}</td>
                    {% if request.user.user_profile.role_type == "HOS" %}
                        <td><a href="{% url 'update_user_info' user_id=user.id%}"><i class="fa fa-edit"></i> Update</a></td>
                    {% endif %}
                    <td><a href="{% url 'view_user' user_id=user.id%}"><i class="fa fa-eye" aria-hidden="true"></i> View</a></td>
                    <td><a href="#"><i class="fas fa-trash ml-1"> Delete</i></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

{% endblock content %}